apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-02T12:01:09Z"
  labels:
    app: grafana
  name: grafana
  namespace: observability
  resourceVersion: "103285"
  uid: e7f9f53f-204d-4b5f-a08c-12988ed96a02
spec:
  clusterIP: 10.96.109.62
  clusterIPs:
  - 10.96.109.62
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
