apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"loki","namespace":"observability"},"spec":{"ports":[{"port":3100,"targetPort":3100}],"selector":{"app":"loki"}}}
  creationTimestamp: "2026-06-01T15:22:43Z"
  name: loki
  namespace: observability
  resourceVersion: "4140"
  uid: ce7f39a4-a48b-4dd4-92bc-238c4e96a8d7
spec:
  clusterIP: 10.96.161.81
  clusterIPs:
  - 10.96.161.81
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
