apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-02T13:18:38Z"
  name: node-exporter
  namespace: observability
  resourceVersion: "109528"
  uid: e2a155e6-f04d-4883-9ad0-2395542af98a
spec:
  clusterIP: 10.96.160.178
  clusterIPs:
  - 10.96.160.178
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
